### ISSUE TITLE
pb_clamp() buggy

### ISSUE THREAD

**Issue by hasufell** [libtom/libtompoly#3]
Either I don't understand how to use it, or it is buggy.

E.g. imagine a polynomial x^11-1 with "used" set to 2
Now when you call clamp on it, it will set "used" to 1

It seems this line https://github.com/libtom/libtompoly/blob/develop/pb_clamp.c#L16 makes some assumptions about the character of the polynom?

Currently I have to work around it via something like this

```
int get_degree(pb_poly *poly)
{
    int count = 0, i;

    for (i = 0; i < poly->alloc; i++)
        if (mp_iszero(&(poly->terms[i])) == MP_NO)
            count = i;

    return count;
}
```

**Comment by hasufell** [comment]
That said... the pb_cmp() method comparing the values of a->used etc seems like the wrong approach.

**Comment by tomstdenis** [comment]
This is from a while ago ... Not that this project is active ... but if you have x^11 - 1 then used should be 12 not 2.  You have 12 terms {1,0,0,0,0,0,0,0,0,0,0,-1}.  The clamp uses a while digit == 0 logic so it'll hit the first {1} and then drop out of the while loop.

**Comment by hasufell** [comment]
I don't even know what I did there back then. It was a uni project and I ended up using FLINT. Can probably be closed.

**Comment by tomstdenis** [comment]
Fair enough.  LTP was a project I started towards the end of my FOSS career.  It wasn't finished nor well supported.  :-)
